version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: ./backend/.env
    ports:
      - "5050:5050"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PW: ${DATABASE_PW}
