version: '3.8'
services:
  backend:
    build: ./backend  # Build the backend container using the Dockerfile in the ./backend directory
    ports:
      - "5000:5000"   # Expose port 5000 of the container on port 5000 of the host
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_PW=${DB_PW}
      - DATABASE_NAME=${DB_NAME}
    depends_on:
      - db            # Ensure the database container starts before the backend

  db:
    image: postgres:14
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"   # Expose PostgreSQL on port 5432
