name: ufc_elo_engine
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pip
  - beautifulsoup4
  - seaborn
  - pandas
  - requests
  - ipykernel
  - plotly=5.24.1
  - nbformat>=4.2.0
  - numexpr
  - bottleneck
  - python-kaleido
  - fastapi
  - uvicorn
  - SQLAlchemy
  - psycopg2-binary
  - psycopg2
  - database
  - python-dotenv
  - Scrapy
