name: Docker Compose CI

on:
  push:
    branches: [ "main", "austin" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Load environment variables
      run: |
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
        echo "DATABASE_PW=${{ secrets.DATABASE_PW }}" >> $GITHUB_ENV
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> $GITHUB_ENV
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> $GITHUB_ENV

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Set up Docker Compose
      run: |
        echo "COMPOSE_PROJECT_NAME=github_actions_ci" >> $GITHUB_ENV

    - name: Build and Run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d
    
    - name: List Running Containers
      run: docker ps -a

    - name: Check Backend Logs
      run: |
        CONTAINER_ID=$(docker ps -aq --filter "ancestor=backend_service")
        if [ -n "$CONTAINER_ID" ]; then
          docker logs "$CONTAINER_ID" || echo "No logs available."
        else
          echo "No backend container running."
        fi
        
        DB_CONTAINER_ID=$(docker ps -aq --filter "ancestor=db_container")
        if [ -n "$DB_CONTAINER_ID" ]; then
          echo "Fetching logs for db_container..."
          docker logs "$DB_CONTAINER_ID" || echo "No logs available for db_container."
        else
          echo "No db container running."
        fi
